sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker run --rm travis-ci-build-stages-demo ansible --version
      - docker run --rm travis-ci-build-stages-demo ansible-lint --version
      - docker run --rm travis-ci-build-stages-demo ssh -V     