name: Master CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t ansible-lint .
      - name: Tags
        run: |
          docker tag ansible-lint ${{ github.repository }}:${{ github.sha }}
          docker tag ansible-lint ${{ github.repository }}:latest
      - name: check install
        run: |
          docker images
          docker run --rm ${{ github.repository }}:${{ github.sha }} ansible --version
          docker run --rm ${{ github.repository }}:${{ github.sha }} ansible-lint --version
          docker run --rm ${{ github.repository }}:${{ github.sha }} ssh -V
          docker run --rm ${{ github.repository }}:${{ github.sha }} bash --version
      - name: Push to Docker Hub
        run: |
          docker push ${{ github.repository }}:${{ github.sha }}
          docker push ${{ github.repository }}:latest
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
