name: Master CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Docker:
    runs-on: ubuntu-latest
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Build and push latest
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest


      - name: check install
        run: |
          docker images
          docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} ansible --version
          docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} ansible-lint --version
          docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} ssh -V
          docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} bash --version
